services:
  # nginx:
  #   image: nginx:apline
  #   container_name: rkm_nginx
  #   ports:
  #     - "8081:80"
  #   volumes:
  #       - ./site/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #       - ./site:/usr/share/nginx/html:ro
  #   depends_on:
  #     - frontend
  #     - backend
  frontend:
    image: rkm_events_frontend
    build: 
       context: ./frontend_admin
       dockerfile: Dockerfile
    working_dir: /frontend_admin
    env_file:
      - ./frontend_admin/.env.local
    ports:
      - "3001:3000"
    volumes:
      - /frontend_admin/node_modules

  backend:
    image: rkm_events_backend
    build: 
       context: ./backend_admin
       dockerfile: Dockerfile
    working_dir: /backend_admin
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./backend_admin:/backend_admin
    depends_on:
      - db
    command: gunicorn backend_admin.wsgi:application --bind 0.0.0.0:8001
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
   

