# Generated by Django 4.2.23 on 2025-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-start_date', '-date']},
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the event', null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the event', null=True),
        ),
    ]
