# Generated by Django 4.2.23 on 2025-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options_events_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(blank=True, help_text='Formatted date string or date range', max_length=200, null=True),
        ),
    ]
