# Generated by Django 4.2.10 on 2025-08-24 23:44

import audios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the audio file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the audio content', null=True)),
                ('audio_file', models.FileField(help_text='Upload audio file (MP3, WAV, M4A, AAC, OGG)', upload_to=audios.models.audio_file_path)),
                ('duration', models.DurationField(blank=True, help_text='Duration of the audio', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('format', models.CharField(blank=True, choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A'), ('aac', 'AAC'), ('ogg', 'OGG')], max_length=10, null=True)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this audio is publicly accessible')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured audio for homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_events', models.ManyToManyField(blank=True, help_text='Events related to this audio', related_name='audios', to='events.events')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this audio', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'ordering': ['-created_at'],
            },
        ),
    ]
