# Generated by Django 4.2.10 on 2025-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether this audio is published and available in public API'),
        ),
    ]
