# Generated by Django 4.2.10 on 2025-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Cover image URL from ImgBB', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='cover_image_name',
            field=models.CharField(blank=True, help_text='Cover image filename', max_length=200, null=True),
        ),
    ]
