# Generated by Django 4.2.10 on 2025-08-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_audio_cover_image_audio_cover_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='b2_download_url',
            field=models.URLField(blank=True, help_text='Download URL from Backblaze B2', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='b2_file_id',
            field=models.CharField(blank=True, help_text='File ID in Backblaze B2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='b2_file_name',
            field=models.CharField(blank=True, help_text='File name in Backblaze B2', max_length=500, null=True),
        ),
    ]
